name: Docker DEV Image CI

on:
  push:
    branches: [ feature/docker ]
  pull_request:
    branches: [ feature/docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the DEV VERSION Docker image
      run: docker build . --file Dockerfile --tag queue-vk-bot-dev:$(date +%s)
